### ISSUE TITLE
[Feature Request] Replant plants after harvested

### ISSUE THREAD

**Issue by xfl03** [n643064/Harvest-Fabric#1]
Could this mod replant plants after harvested it?

**Comment by n643064** [comment]
@xfl03 It could, but it might trip some anti-cheats, and such feature would generally be more fit for a server-side mod, like [this](https://modrinth.com/mod/right-click-harvest) one.

**Comment by xfl03** [comment]
Thanks, I made this feature in server side.  
https://github.com/xfl03/YetAnotherHarvest
