### ISSUE TITLE
Right-click while paused / in menus triggers break

### ISSUE THREAD

**Issue by YoshiRulz** [n643064/Harvest-Fabric#3]
This affects singleplayer, LAN (as host), and multiplayer. Repro'd with version 1.3.0 of the mod on Minecraft 1.20.4 and version 1.4.0 of the mod on Minecraft 1.19.4.

**Comment by n643064** [comment]
Fixed in [1.3.1](https://modrinth.com/mod/harvest/version/1.3.1)
